channels:
- conda-forge
dependencies:
- python=3.12.4
- pip<=24.0
- pip:
  - mlflow==3.1.0
  - cloudpickle==3.1.1
  - numpy==2.2.3
  - psutil==6.0.0
  - scikit-learn==1.5.1
  - scipy==1.14.0
name: mlflow-env
