name: MLflow CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        environment-file: MLProject/conda.yaml
        activate-environment: student_performance_env

    - name: Install MLflow
      run: |
        conda activate student_performance_env
        pip install mlflow

    - name: Start MLflow server
      run: |
        mlflow server --host 0.0.0.0 --port 5000 &
        sleep 10  # Wait for server to start

    - name: Run MLflow project
      env:
        MLFLOW_TRACKING_URI: http://localhost:5000
      run: |
        conda activate student_performance_env
        mlflow run MLProject -P MLFLOW_TRACKING_URI=$MLFLOW_TRACKING_URI

    - name: Upload MLflow artifacts
      uses: actions/upload-artifact@v3
      with:
        name: mlflow-artifacts
        path: mlruns/