name: workflow-ci

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

env:
    CSV_URL: "MLProject/Student_performance_processed_data.csv"
    TARGET_VAR: "GradeClass"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:

            - uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12.9'

            - name: Check Env
              run: |
                echo $CSV_URL
                echo $TARGET_VAR

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install mlflow scikit-learn pandas numpy

            - name: Run as a MLflow
              run: |
                mlflow run MLProject --env-manager virtualenv

            - name: set up git lfs
              run: |
                git config --global user.name "${{ secrets.USERNAME }}"
                git config --global user.email "${{ secrets.EMAIL }}"
                git lfs install
                git lfs track "mlruns/**"
                git add .gitattributes
                git commit -m "Track large files in mlruns with Git LFS" || true
                git push origin master

            - name: save mlruns to repo
              run: |
                git config --global user.name "${{ secrets.USERNAME }}"
                git config --global user.email "${{ secrets.EMAIL }}"
                git add -f mlruns/
                git commit -m "Save mlruns from CI run" || true
                git push origin master

            - name: get latest mlflow run_id
              run: |
                RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
                echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
                echo "Latest run_id: $RUN_ID"