name: workflow-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Tambahkan ini agar bisa dijalankan manual juga

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: MLProject
        run: |
          pip install -r requirements.txt
          pip install mlflow

      - name: Run MLflow Project
        working-directory: MLProject
        run: |
          mlflow run . --entry-point main

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: MLProject/mlruns